GET http://localhost:3000/admin/getAllLoans
Content-Type: application/json
x-auth-token:eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiU3RldmUgT3Nvcm8iLCJlbWFpbCI6InRvbXN0ZXZlMTg3QGdtYWlsLmNvbSIsImlkTnVtYmVyIjoiMSIsInBob25lTnVtYmVyIjoiKzI1NDc1ODQ4MTMyMCIsInVzZXJJZCI6MSwiaWF0IjoxNjg5MjMwNTg1LCJleHAiOjE2ODkyMzc3ODV9.KCWyhAA4JYR5kLri-4-MAx0OiahTNccrC81R1dfoE3k