GET localhost:3000/loan/1
x-auth-token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiU3RldmUgT3Nvcm8iLCJlbWFpbCI6InRvbXN0ZXZlMTg3QGdtYWlsLmNvbSIsImlkTnVtYmVyIjoiMSIsInBob25lTnVtYmVyIjoiKzI1NDc1ODQ4MTMyMCIsInVzZXJJZCI6MSwiaWF0IjoxNjg5MzEzNzY0LCJleHAiOjE2ODkzMjA5NjR9.Jbs6fjbnxbe-NP9vy7Oks5wVm4wsIo73CWr0lUGUKVY